// tslint:disable-next-line: no-empty-interface
export interface IEvent{
    userId : number
    eventName : string
    eventDescription : string
    eventImageUrl : string
    eventLocation : string
    eventFromDate : Date
    eventToDate : Date
    organizedType : string
    organizerName : string
    organizerPhone : number
    organizerEmail : string
    eventType : string
    eventHeadCount : string
    ticketQuantity : string
    ticketPrice : string
    eventCategory : string
}
